version: '3.7'

services:
  # PHP Service
  php:
    build: '.'
    container_name: laravel-php
    depends_on:
      - composer_installation
    networks:
      - backend
    volumes:
      - ./public_html:/var/www/html
      - ./apache2/log:/var/log/apache2

  # Apache Service
  apache:
    build: './apache2/'
    container_name: laravel-apache
    depends_on:
      - php
      - pgsql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public_html:/var/www/html
      - ./apache2/log:/var/log/apache2

  #PostgreSQL Service
  pgsql:
    image: postgres:12.0-alpine
    container_name: laravel-pgsql
    working_dir: /data/pgsql
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    - ./public_html/database/legacy:/var/lib/postgresql
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432
    networks:
      - backend
  
  composer_installation:
   container_name: composer_installation
   image: composer
   volumes:
     - ./public_html/:/app
   command: sh -c "composer install --ignore-platform-reqs && cp .env.example .env && php artisan key:generate"

networks:
  frontend:
  backend:
