#!/usr/bin/env bash
set -e
. "$BAGCLI_WORKDIR/common"

cli_help_deploy() {
  echo "
Command: populate
Warning: This command removes all data
Usage:
  populate"
  exit 1
}

[ ! -n "$1" ] && cli_help_deploy

sudo docker-compose exec php php artisan sed:comment migrations "\$table->foreign"
sudo docker-compose exec php php artisan migrate:fresh
sudo docker-compose exec php php artisan sed:uncomment migrations "\$table->foreign"
sudo docker exec -it laravel-pgsql psql -h pgsql -U pguser pgdb -f /var/lib/postgresql/cpi.sql
sudo docker-compose exec php php artisan migrate:refresh --seed